// generated by scripts/gen-php-metadata from php 8.5.4 reflection; do not edit
pub const Constant = struct { name: []const u8, id: i64 };

// every T_* constant, aliases included
pub const constants = [_]Constant{
    .{ .name = "T_LNUMBER", .id = 260 },
    .{ .name = "T_DNUMBER", .id = 261 },
    .{ .name = "T_STRING", .id = 262 },
    .{ .name = "T_NAME_FULLY_QUALIFIED", .id = 263 },
    .{ .name = "T_NAME_RELATIVE", .id = 264 },
    .{ .name = "T_NAME_QUALIFIED", .id = 265 },
    .{ .name = "T_VARIABLE", .id = 266 },
    .{ .name = "T_INLINE_HTML", .id = 267 },
    .{ .name = "T_ENCAPSED_AND_WHITESPACE", .id = 268 },
    .{ .name = "T_CONSTANT_ENCAPSED_STRING", .id = 269 },
    .{ .name = "T_STRING_VARNAME", .id = 270 },
    .{ .name = "T_NUM_STRING", .id = 271 },
    .{ .name = "T_INCLUDE", .id = 272 },
    .{ .name = "T_INCLUDE_ONCE", .id = 273 },
    .{ .name = "T_EVAL", .id = 274 },
    .{ .name = "T_REQUIRE", .id = 275 },
    .{ .name = "T_REQUIRE_ONCE", .id = 276 },
    .{ .name = "T_LOGICAL_OR", .id = 277 },
    .{ .name = "T_LOGICAL_XOR", .id = 278 },
    .{ .name = "T_LOGICAL_AND", .id = 279 },
    .{ .name = "T_PRINT", .id = 280 },
    .{ .name = "T_YIELD", .id = 281 },
    .{ .name = "T_YIELD_FROM", .id = 282 },
    .{ .name = "T_INSTANCEOF", .id = 283 },
    .{ .name = "T_NEW", .id = 284 },
    .{ .name = "T_CLONE", .id = 285 },
    .{ .name = "T_EXIT", .id = 286 },
    .{ .name = "T_IF", .id = 287 },
    .{ .name = "T_ELSEIF", .id = 288 },
    .{ .name = "T_ELSE", .id = 289 },
    .{ .name = "T_ENDIF", .id = 290 },
    .{ .name = "T_ECHO", .id = 291 },
    .{ .name = "T_DO", .id = 292 },
    .{ .name = "T_WHILE", .id = 293 },
    .{ .name = "T_ENDWHILE", .id = 294 },
    .{ .name = "T_FOR", .id = 295 },
    .{ .name = "T_ENDFOR", .id = 296 },
    .{ .name = "T_FOREACH", .id = 297 },
    .{ .name = "T_ENDFOREACH", .id = 298 },
    .{ .name = "T_DECLARE", .id = 299 },
    .{ .name = "T_ENDDECLARE", .id = 300 },
    .{ .name = "T_AS", .id = 301 },
    .{ .name = "T_SWITCH", .id = 302 },
    .{ .name = "T_ENDSWITCH", .id = 303 },
    .{ .name = "T_CASE", .id = 304 },
    .{ .name = "T_DEFAULT", .id = 305 },
    .{ .name = "T_MATCH", .id = 306 },
    .{ .name = "T_BREAK", .id = 307 },
    .{ .name = "T_CONTINUE", .id = 308 },
    .{ .name = "T_GOTO", .id = 309 },
    .{ .name = "T_FUNCTION", .id = 310 },
    .{ .name = "T_FN", .id = 311 },
    .{ .name = "T_CONST", .id = 312 },
    .{ .name = "T_RETURN", .id = 313 },
    .{ .name = "T_TRY", .id = 314 },
    .{ .name = "T_CATCH", .id = 315 },
    .{ .name = "T_FINALLY", .id = 316 },
    .{ .name = "T_THROW", .id = 317 },
    .{ .name = "T_USE", .id = 318 },
    .{ .name = "T_INSTEADOF", .id = 319 },
    .{ .name = "T_GLOBAL", .id = 320 },
    .{ .name = "T_STATIC", .id = 321 },
    .{ .name = "T_ABSTRACT", .id = 322 },
    .{ .name = "T_FINAL", .id = 323 },
    .{ .name = "T_PRIVATE", .id = 324 },
    .{ .name = "T_PROTECTED", .id = 325 },
    .{ .name = "T_PUBLIC", .id = 326 },
    .{ .name = "T_PRIVATE_SET", .id = 327 },
    .{ .name = "T_PROTECTED_SET", .id = 328 },
    .{ .name = "T_PUBLIC_SET", .id = 329 },
    .{ .name = "T_READONLY", .id = 330 },
    .{ .name = "T_VAR", .id = 331 },
    .{ .name = "T_UNSET", .id = 332 },
    .{ .name = "T_ISSET", .id = 333 },
    .{ .name = "T_EMPTY", .id = 334 },
    .{ .name = "T_HALT_COMPILER", .id = 335 },
    .{ .name = "T_CLASS", .id = 336 },
    .{ .name = "T_TRAIT", .id = 337 },
    .{ .name = "T_INTERFACE", .id = 338 },
    .{ .name = "T_ENUM", .id = 339 },
    .{ .name = "T_EXTENDS", .id = 340 },
    .{ .name = "T_IMPLEMENTS", .id = 341 },
    .{ .name = "T_NAMESPACE", .id = 342 },
    .{ .name = "T_LIST", .id = 343 },
    .{ .name = "T_ARRAY", .id = 344 },
    .{ .name = "T_CALLABLE", .id = 345 },
    .{ .name = "T_LINE", .id = 346 },
    .{ .name = "T_FILE", .id = 347 },
    .{ .name = "T_DIR", .id = 348 },
    .{ .name = "T_CLASS_C", .id = 349 },
    .{ .name = "T_TRAIT_C", .id = 350 },
    .{ .name = "T_METHOD_C", .id = 351 },
    .{ .name = "T_FUNC_C", .id = 352 },
    .{ .name = "T_PROPERTY_C", .id = 353 },
    .{ .name = "T_NS_C", .id = 354 },
    .{ .name = "T_ATTRIBUTE", .id = 355 },
    .{ .name = "T_PLUS_EQUAL", .id = 356 },
    .{ .name = "T_MINUS_EQUAL", .id = 357 },
    .{ .name = "T_MUL_EQUAL", .id = 358 },
    .{ .name = "T_DIV_EQUAL", .id = 359 },
    .{ .name = "T_CONCAT_EQUAL", .id = 360 },
    .{ .name = "T_MOD_EQUAL", .id = 361 },
    .{ .name = "T_AND_EQUAL", .id = 362 },
    .{ .name = "T_OR_EQUAL", .id = 363 },
    .{ .name = "T_XOR_EQUAL", .id = 364 },
    .{ .name = "T_SL_EQUAL", .id = 365 },
    .{ .name = "T_SR_EQUAL", .id = 366 },
    .{ .name = "T_COALESCE_EQUAL", .id = 367 },
    .{ .name = "T_BOOLEAN_OR", .id = 368 },
    .{ .name = "T_BOOLEAN_AND", .id = 369 },
    .{ .name = "T_IS_EQUAL", .id = 370 },
    .{ .name = "T_IS_NOT_EQUAL", .id = 371 },
    .{ .name = "T_IS_IDENTICAL", .id = 372 },
    .{ .name = "T_IS_NOT_IDENTICAL", .id = 373 },
    .{ .name = "T_IS_SMALLER_OR_EQUAL", .id = 374 },
    .{ .name = "T_IS_GREATER_OR_EQUAL", .id = 375 },
    .{ .name = "T_SPACESHIP", .id = 376 },
    .{ .name = "T_SL", .id = 377 },
    .{ .name = "T_SR", .id = 378 },
    .{ .name = "T_INC", .id = 379 },
    .{ .name = "T_DEC", .id = 380 },
    .{ .name = "T_INT_CAST", .id = 381 },
    .{ .name = "T_DOUBLE_CAST", .id = 382 },
    .{ .name = "T_STRING_CAST", .id = 383 },
    .{ .name = "T_ARRAY_CAST", .id = 384 },
    .{ .name = "T_OBJECT_CAST", .id = 385 },
    .{ .name = "T_BOOL_CAST", .id = 386 },
    .{ .name = "T_UNSET_CAST", .id = 387 },
    .{ .name = "T_VOID_CAST", .id = 388 },
    .{ .name = "T_OBJECT_OPERATOR", .id = 389 },
    .{ .name = "T_NULLSAFE_OBJECT_OPERATOR", .id = 390 },
    .{ .name = "T_DOUBLE_ARROW", .id = 391 },
    .{ .name = "T_COMMENT", .id = 392 },
    .{ .name = "T_DOC_COMMENT", .id = 393 },
    .{ .name = "T_OPEN_TAG", .id = 394 },
    .{ .name = "T_OPEN_TAG_WITH_ECHO", .id = 395 },
    .{ .name = "T_CLOSE_TAG", .id = 396 },
    .{ .name = "T_WHITESPACE", .id = 397 },
    .{ .name = "T_START_HEREDOC", .id = 398 },
    .{ .name = "T_END_HEREDOC", .id = 399 },
    .{ .name = "T_DOLLAR_OPEN_CURLY_BRACES", .id = 400 },
    .{ .name = "T_CURLY_OPEN", .id = 401 },
    .{ .name = "T_PAAMAYIM_NEKUDOTAYIM", .id = 402 },
    .{ .name = "T_NS_SEPARATOR", .id = 403 },
    .{ .name = "T_ELLIPSIS", .id = 404 },
    .{ .name = "T_COALESCE", .id = 405 },
    .{ .name = "T_POW", .id = 406 },
    .{ .name = "T_POW_EQUAL", .id = 407 },
    .{ .name = "T_PIPE", .id = 408 },
    .{ .name = "T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG", .id = 409 },
    .{ .name = "T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG", .id = 410 },
    .{ .name = "T_BAD_CHARACTER", .id = 411 },
    .{ .name = "T_DOUBLE_COLON", .id = 402 },
};

// token_name(): the canonical name of each id
pub const names = [_]Constant{
    .{ .name = "T_LNUMBER", .id = 260 },
    .{ .name = "T_DNUMBER", .id = 261 },
    .{ .name = "T_STRING", .id = 262 },
    .{ .name = "T_NAME_FULLY_QUALIFIED", .id = 263 },
    .{ .name = "T_NAME_RELATIVE", .id = 264 },
    .{ .name = "T_NAME_QUALIFIED", .id = 265 },
    .{ .name = "T_VARIABLE", .id = 266 },
    .{ .name = "T_INLINE_HTML", .id = 267 },
    .{ .name = "T_ENCAPSED_AND_WHITESPACE", .id = 268 },
    .{ .name = "T_CONSTANT_ENCAPSED_STRING", .id = 269 },
    .{ .name = "T_STRING_VARNAME", .id = 270 },
    .{ .name = "T_NUM_STRING", .id = 271 },
    .{ .name = "T_INCLUDE", .id = 272 },
    .{ .name = "T_INCLUDE_ONCE", .id = 273 },
    .{ .name = "T_EVAL", .id = 274 },
    .{ .name = "T_REQUIRE", .id = 275 },
    .{ .name = "T_REQUIRE_ONCE", .id = 276 },
    .{ .name = "T_LOGICAL_OR", .id = 277 },
    .{ .name = "T_LOGICAL_XOR", .id = 278 },
    .{ .name = "T_LOGICAL_AND", .id = 279 },
    .{ .name = "T_PRINT", .id = 280 },
    .{ .name = "T_YIELD", .id = 281 },
    .{ .name = "T_YIELD_FROM", .id = 282 },
    .{ .name = "T_INSTANCEOF", .id = 283 },
    .{ .name = "T_NEW", .id = 284 },
    .{ .name = "T_CLONE", .id = 285 },
    .{ .name = "T_EXIT", .id = 286 },
    .{ .name = "T_IF", .id = 287 },
    .{ .name = "T_ELSEIF", .id = 288 },
    .{ .name = "T_ELSE", .id = 289 },
    .{ .name = "T_ENDIF", .id = 290 },
    .{ .name = "T_ECHO", .id = 291 },
    .{ .name = "T_DO", .id = 292 },
    .{ .name = "T_WHILE", .id = 293 },
    .{ .name = "T_ENDWHILE", .id = 294 },
    .{ .name = "T_FOR", .id = 295 },
    .{ .name = "T_ENDFOR", .id = 296 },
    .{ .name = "T_FOREACH", .id = 297 },
    .{ .name = "T_ENDFOREACH", .id = 298 },
    .{ .name = "T_DECLARE", .id = 299 },
    .{ .name = "T_ENDDECLARE", .id = 300 },
    .{ .name = "T_AS", .id = 301 },
    .{ .name = "T_SWITCH", .id = 302 },
    .{ .name = "T_ENDSWITCH", .id = 303 },
    .{ .name = "T_CASE", .id = 304 },
    .{ .name = "T_DEFAULT", .id = 305 },
    .{ .name = "T_MATCH", .id = 306 },
    .{ .name = "T_BREAK", .id = 307 },
    .{ .name = "T_CONTINUE", .id = 308 },
    .{ .name = "T_GOTO", .id = 309 },
    .{ .name = "T_FUNCTION", .id = 310 },
    .{ .name = "T_FN", .id = 311 },
    .{ .name = "T_CONST", .id = 312 },
    .{ .name = "T_RETURN", .id = 313 },
    .{ .name = "T_TRY", .id = 314 },
    .{ .name = "T_CATCH", .id = 315 },
    .{ .name = "T_FINALLY", .id = 316 },
    .{ .name = "T_THROW", .id = 317 },
    .{ .name = "T_USE", .id = 318 },
    .{ .name = "T_INSTEADOF", .id = 319 },
    .{ .name = "T_GLOBAL", .id = 320 },
    .{ .name = "T_STATIC", .id = 321 },
    .{ .name = "T_ABSTRACT", .id = 322 },
    .{ .name = "T_FINAL", .id = 323 },
    .{ .name = "T_PRIVATE", .id = 324 },
    .{ .name = "T_PROTECTED", .id = 325 },
    .{ .name = "T_PUBLIC", .id = 326 },
    .{ .name = "T_PRIVATE_SET", .id = 327 },
    .{ .name = "T_PROTECTED_SET", .id = 328 },
    .{ .name = "T_PUBLIC_SET", .id = 329 },
    .{ .name = "T_READONLY", .id = 330 },
    .{ .name = "T_VAR", .id = 331 },
    .{ .name = "T_UNSET", .id = 332 },
    .{ .name = "T_ISSET", .id = 333 },
    .{ .name = "T_EMPTY", .id = 334 },
    .{ .name = "T_HALT_COMPILER", .id = 335 },
    .{ .name = "T_CLASS", .id = 336 },
    .{ .name = "T_TRAIT", .id = 337 },
    .{ .name = "T_INTERFACE", .id = 338 },
    .{ .name = "T_ENUM", .id = 339 },
    .{ .name = "T_EXTENDS", .id = 340 },
    .{ .name = "T_IMPLEMENTS", .id = 341 },
    .{ .name = "T_NAMESPACE", .id = 342 },
    .{ .name = "T_LIST", .id = 343 },
    .{ .name = "T_ARRAY", .id = 344 },
    .{ .name = "T_CALLABLE", .id = 345 },
    .{ .name = "T_LINE", .id = 346 },
    .{ .name = "T_FILE", .id = 347 },
    .{ .name = "T_DIR", .id = 348 },
    .{ .name = "T_CLASS_C", .id = 349 },
    .{ .name = "T_TRAIT_C", .id = 350 },
    .{ .name = "T_METHOD_C", .id = 351 },
    .{ .name = "T_FUNC_C", .id = 352 },
    .{ .name = "T_PROPERTY_C", .id = 353 },
    .{ .name = "T_NS_C", .id = 354 },
    .{ .name = "T_ATTRIBUTE", .id = 355 },
    .{ .name = "T_PLUS_EQUAL", .id = 356 },
    .{ .name = "T_MINUS_EQUAL", .id = 357 },
    .{ .name = "T_MUL_EQUAL", .id = 358 },
    .{ .name = "T_DIV_EQUAL", .id = 359 },
    .{ .name = "T_CONCAT_EQUAL", .id = 360 },
    .{ .name = "T_MOD_EQUAL", .id = 361 },
    .{ .name = "T_AND_EQUAL", .id = 362 },
    .{ .name = "T_OR_EQUAL", .id = 363 },
    .{ .name = "T_XOR_EQUAL", .id = 364 },
    .{ .name = "T_SL_EQUAL", .id = 365 },
    .{ .name = "T_SR_EQUAL", .id = 366 },
    .{ .name = "T_COALESCE_EQUAL", .id = 367 },
    .{ .name = "T_BOOLEAN_OR", .id = 368 },
    .{ .name = "T_BOOLEAN_AND", .id = 369 },
    .{ .name = "T_IS_EQUAL", .id = 370 },
    .{ .name = "T_IS_NOT_EQUAL", .id = 371 },
    .{ .name = "T_IS_IDENTICAL", .id = 372 },
    .{ .name = "T_IS_NOT_IDENTICAL", .id = 373 },
    .{ .name = "T_IS_SMALLER_OR_EQUAL", .id = 374 },
    .{ .name = "T_IS_GREATER_OR_EQUAL", .id = 375 },
    .{ .name = "T_SPACESHIP", .id = 376 },
    .{ .name = "T_SL", .id = 377 },
    .{ .name = "T_SR", .id = 378 },
    .{ .name = "T_INC", .id = 379 },
    .{ .name = "T_DEC", .id = 380 },
    .{ .name = "T_INT_CAST", .id = 381 },
    .{ .name = "T_DOUBLE_CAST", .id = 382 },
    .{ .name = "T_STRING_CAST", .id = 383 },
    .{ .name = "T_ARRAY_CAST", .id = 384 },
    .{ .name = "T_OBJECT_CAST", .id = 385 },
    .{ .name = "T_BOOL_CAST", .id = 386 },
    .{ .name = "T_UNSET_CAST", .id = 387 },
    .{ .name = "T_VOID_CAST", .id = 388 },
    .{ .name = "T_OBJECT_OPERATOR", .id = 389 },
    .{ .name = "T_NULLSAFE_OBJECT_OPERATOR", .id = 390 },
    .{ .name = "T_DOUBLE_ARROW", .id = 391 },
    .{ .name = "T_COMMENT", .id = 392 },
    .{ .name = "T_DOC_COMMENT", .id = 393 },
    .{ .name = "T_OPEN_TAG", .id = 394 },
    .{ .name = "T_OPEN_TAG_WITH_ECHO", .id = 395 },
    .{ .name = "T_CLOSE_TAG", .id = 396 },
    .{ .name = "T_WHITESPACE", .id = 397 },
    .{ .name = "T_START_HEREDOC", .id = 398 },
    .{ .name = "T_END_HEREDOC", .id = 399 },
    .{ .name = "T_DOLLAR_OPEN_CURLY_BRACES", .id = 400 },
    .{ .name = "T_CURLY_OPEN", .id = 401 },
    .{ .name = "T_DOUBLE_COLON", .id = 402 },
    .{ .name = "T_NS_SEPARATOR", .id = 403 },
    .{ .name = "T_ELLIPSIS", .id = 404 },
    .{ .name = "T_COALESCE", .id = 405 },
    .{ .name = "T_POW", .id = 406 },
    .{ .name = "T_POW_EQUAL", .id = 407 },
    .{ .name = "T_PIPE", .id = 408 },
    .{ .name = "T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG", .id = 409 },
    .{ .name = "T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG", .id = 410 },
    .{ .name = "T_BAD_CHARACTER", .id = 411 },
};

pub const T_LNUMBER: i64 = 260;
pub const T_DNUMBER: i64 = 261;
pub const T_STRING: i64 = 262;
pub const T_NAME_FULLY_QUALIFIED: i64 = 263;
pub const T_NAME_RELATIVE: i64 = 264;
pub const T_NAME_QUALIFIED: i64 = 265;
pub const T_VARIABLE: i64 = 266;
pub const T_INLINE_HTML: i64 = 267;
pub const T_ENCAPSED_AND_WHITESPACE: i64 = 268;
pub const T_CONSTANT_ENCAPSED_STRING: i64 = 269;
pub const T_STRING_VARNAME: i64 = 270;
pub const T_NUM_STRING: i64 = 271;
pub const T_INCLUDE: i64 = 272;
pub const T_INCLUDE_ONCE: i64 = 273;
pub const T_EVAL: i64 = 274;
pub const T_REQUIRE: i64 = 275;
pub const T_REQUIRE_ONCE: i64 = 276;
pub const T_LOGICAL_OR: i64 = 277;
pub const T_LOGICAL_XOR: i64 = 278;
pub const T_LOGICAL_AND: i64 = 279;
pub const T_PRINT: i64 = 280;
pub const T_YIELD: i64 = 281;
pub const T_YIELD_FROM: i64 = 282;
pub const T_INSTANCEOF: i64 = 283;
pub const T_NEW: i64 = 284;
pub const T_CLONE: i64 = 285;
pub const T_EXIT: i64 = 286;
pub const T_IF: i64 = 287;
pub const T_ELSEIF: i64 = 288;
pub const T_ELSE: i64 = 289;
pub const T_ENDIF: i64 = 290;
pub const T_ECHO: i64 = 291;
pub const T_DO: i64 = 292;
pub const T_WHILE: i64 = 293;
pub const T_ENDWHILE: i64 = 294;
pub const T_FOR: i64 = 295;
pub const T_ENDFOR: i64 = 296;
pub const T_FOREACH: i64 = 297;
pub const T_ENDFOREACH: i64 = 298;
pub const T_DECLARE: i64 = 299;
pub const T_ENDDECLARE: i64 = 300;
pub const T_AS: i64 = 301;
pub const T_SWITCH: i64 = 302;
pub const T_ENDSWITCH: i64 = 303;
pub const T_CASE: i64 = 304;
pub const T_DEFAULT: i64 = 305;
pub const T_MATCH: i64 = 306;
pub const T_BREAK: i64 = 307;
pub const T_CONTINUE: i64 = 308;
pub const T_GOTO: i64 = 309;
pub const T_FUNCTION: i64 = 310;
pub const T_FN: i64 = 311;
pub const T_CONST: i64 = 312;
pub const T_RETURN: i64 = 313;
pub const T_TRY: i64 = 314;
pub const T_CATCH: i64 = 315;
pub const T_FINALLY: i64 = 316;
pub const T_THROW: i64 = 317;
pub const T_USE: i64 = 318;
pub const T_INSTEADOF: i64 = 319;
pub const T_GLOBAL: i64 = 320;
pub const T_STATIC: i64 = 321;
pub const T_ABSTRACT: i64 = 322;
pub const T_FINAL: i64 = 323;
pub const T_PRIVATE: i64 = 324;
pub const T_PROTECTED: i64 = 325;
pub const T_PUBLIC: i64 = 326;
pub const T_PRIVATE_SET: i64 = 327;
pub const T_PROTECTED_SET: i64 = 328;
pub const T_PUBLIC_SET: i64 = 329;
pub const T_READONLY: i64 = 330;
pub const T_VAR: i64 = 331;
pub const T_UNSET: i64 = 332;
pub const T_ISSET: i64 = 333;
pub const T_EMPTY: i64 = 334;
pub const T_HALT_COMPILER: i64 = 335;
pub const T_CLASS: i64 = 336;
pub const T_TRAIT: i64 = 337;
pub const T_INTERFACE: i64 = 338;
pub const T_ENUM: i64 = 339;
pub const T_EXTENDS: i64 = 340;
pub const T_IMPLEMENTS: i64 = 341;
pub const T_NAMESPACE: i64 = 342;
pub const T_LIST: i64 = 343;
pub const T_ARRAY: i64 = 344;
pub const T_CALLABLE: i64 = 345;
pub const T_LINE: i64 = 346;
pub const T_FILE: i64 = 347;
pub const T_DIR: i64 = 348;
pub const T_CLASS_C: i64 = 349;
pub const T_TRAIT_C: i64 = 350;
pub const T_METHOD_C: i64 = 351;
pub const T_FUNC_C: i64 = 352;
pub const T_PROPERTY_C: i64 = 353;
pub const T_NS_C: i64 = 354;
pub const T_ATTRIBUTE: i64 = 355;
pub const T_PLUS_EQUAL: i64 = 356;
pub const T_MINUS_EQUAL: i64 = 357;
pub const T_MUL_EQUAL: i64 = 358;
pub const T_DIV_EQUAL: i64 = 359;
pub const T_CONCAT_EQUAL: i64 = 360;
pub const T_MOD_EQUAL: i64 = 361;
pub const T_AND_EQUAL: i64 = 362;
pub const T_OR_EQUAL: i64 = 363;
pub const T_XOR_EQUAL: i64 = 364;
pub const T_SL_EQUAL: i64 = 365;
pub const T_SR_EQUAL: i64 = 366;
pub const T_COALESCE_EQUAL: i64 = 367;
pub const T_BOOLEAN_OR: i64 = 368;
pub const T_BOOLEAN_AND: i64 = 369;
pub const T_IS_EQUAL: i64 = 370;
pub const T_IS_NOT_EQUAL: i64 = 371;
pub const T_IS_IDENTICAL: i64 = 372;
pub const T_IS_NOT_IDENTICAL: i64 = 373;
pub const T_IS_SMALLER_OR_EQUAL: i64 = 374;
pub const T_IS_GREATER_OR_EQUAL: i64 = 375;
pub const T_SPACESHIP: i64 = 376;
pub const T_SL: i64 = 377;
pub const T_SR: i64 = 378;
pub const T_INC: i64 = 379;
pub const T_DEC: i64 = 380;
pub const T_INT_CAST: i64 = 381;
pub const T_DOUBLE_CAST: i64 = 382;
pub const T_STRING_CAST: i64 = 383;
pub const T_ARRAY_CAST: i64 = 384;
pub const T_OBJECT_CAST: i64 = 385;
pub const T_BOOL_CAST: i64 = 386;
pub const T_UNSET_CAST: i64 = 387;
pub const T_VOID_CAST: i64 = 388;
pub const T_OBJECT_OPERATOR: i64 = 389;
pub const T_NULLSAFE_OBJECT_OPERATOR: i64 = 390;
pub const T_DOUBLE_ARROW: i64 = 391;
pub const T_COMMENT: i64 = 392;
pub const T_DOC_COMMENT: i64 = 393;
pub const T_OPEN_TAG: i64 = 394;
pub const T_OPEN_TAG_WITH_ECHO: i64 = 395;
pub const T_CLOSE_TAG: i64 = 396;
pub const T_WHITESPACE: i64 = 397;
pub const T_START_HEREDOC: i64 = 398;
pub const T_END_HEREDOC: i64 = 399;
pub const T_DOLLAR_OPEN_CURLY_BRACES: i64 = 400;
pub const T_CURLY_OPEN: i64 = 401;
pub const T_PAAMAYIM_NEKUDOTAYIM: i64 = 402;
pub const T_NS_SEPARATOR: i64 = 403;
pub const T_ELLIPSIS: i64 = 404;
pub const T_COALESCE: i64 = 405;
pub const T_POW: i64 = 406;
pub const T_POW_EQUAL: i64 = 407;
pub const T_PIPE: i64 = 408;
pub const T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG: i64 = 409;
pub const T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG: i64 = 410;
pub const T_BAD_CHARACTER: i64 = 411;
pub const T_DOUBLE_COLON: i64 = 402;
